# Generated by Django 2.0.2 on 2018-04-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcdata', '0003_pricedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='price',
            field=models.TextField(default=''),
        ),
    ]
