# Generated by Django 2.0.2 on 2018-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcdata', '0004_pricedata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='time',
            field=models.DateField(verbose_name='date get'),
        ),
    ]
