# Generated by Django 2.0.2 on 2018-04-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcdata', '0006_auto_20180424_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
