# Generated by Django 2.0.4 on 2018-04-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcdata', '0007_auto_20180424_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='XMRData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.TextField(default='')),
            ],
        ),
    ]
